name: Docker Build Only

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create .env placeholder
      run: |
        echo "REACT_APP_API_URL=http://localhost:4000" > frontend/.env
        echo "PORT=8080" > backend/.env

    - name: Build containers
      run: docker compose build
